import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "@/context/UserContext";
import BootstrapClient from "./components/libraries/Bootstrap";
import Toast from "./components/libraries/Toast";
import Header from "./components/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <UserContextProvider>
          <div className="container-fluid">
            <Header />
            <div className="container">{children}</div>
            <BootstrapClient />
            <Toast />
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
